
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "CENARIO DIMENSAO ID MAPA NUMBER OBJETO POSICAO STRING TIPO TIPO_TERRENOprogram : scenario\n| program scenarioscenario : CENARIO ID '{' mapa objetos '}' mapa : MAPA '{' dimensao tipo_terreno '}' dimensao : DIMENSAO '=' pair ';' tipo_terreno : TIPO_TERRENO '=' ID ';' objetos :\n| objetos objetoobjeto : OBJETO ID '{' tipo posicao dimensao '}' tipo : TIPO '=' ID ';' posicao : POSICAO '=' pair ';' pair : '(' NUMBER ',' NUMBER ')' "
    
_lr_action_items = {'CENARIO':([0,1,2,4,11,],[3,3,-1,-2,-3,]),'$end':([1,2,4,11,],[0,-1,-2,-3,]),'ID':([3,13,22,32,],[5,16,27,37,]),'{':([5,8,16,],[6,10,20,]),'MAPA':([6,],[8,]),'}':([7,9,12,17,21,28,33,35,39,],[-7,11,-8,21,-4,-5,-6,39,-9,]),'OBJETO':([7,9,12,21,39,],[-7,13,-8,-4,-9,]),'DIMENSAO':([10,30,43,],[15,15,-11,]),'TIPO_TERRENO':([14,28,],[18,-5,]),'=':([15,18,26,31,],[19,22,32,36,]),'(':([19,36,],[24,24,]),'TIPO':([20,],[26,]),';':([23,27,37,40,42,],[28,33,41,43,-12,]),'NUMBER':([24,34,],[29,38,]),'POSICAO':([25,41,],[31,-10,]),',':([29,],[34,]),')':([38,],[42,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'scenario':([0,1,],[2,4,]),'mapa':([6,],[7,]),'objetos':([7,],[9,]),'objeto':([9,],[12,]),'dimensao':([10,30,],[14,35,]),'tipo_terreno':([14,],[17,]),'pair':([19,36,],[23,40,]),'tipo':([20,],[25,]),'posicao':([25,],[30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> scenario','program',1,'p_program','parser.py',8),
  ('program -> program scenario','program',2,'p_program','parser.py',9),
  ('scenario -> CENARIO ID { mapa objetos }','scenario',6,'p_scenario','parser.py',16),
  ('mapa -> MAPA { dimensao tipo_terreno }','mapa',5,'p_mapa','parser.py',25),
  ('dimensao -> DIMENSAO = pair ;','dimensao',4,'p_dimensao','parser.py',34),
  ('tipo_terreno -> TIPO_TERRENO = ID ;','tipo_terreno',4,'p_tipo_terreno','parser.py',41),
  ('objetos -> <empty>','objetos',0,'p_objetos','parser.py',47),
  ('objetos -> objetos objeto','objetos',2,'p_objetos','parser.py',48),
  ('objeto -> OBJETO ID { tipo posicao dimensao }','objeto',7,'p_objeto','parser.py',55),
  ('tipo -> TIPO = ID ;','tipo',4,'p_tipo','parser.py',67),
  ('posicao -> POSICAO = pair ;','posicao',4,'p_posicao','parser.py',73),
  ('pair -> ( NUMBER , NUMBER )','pair',5,'p_pair','parser.py',77),
]
